apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - image: nextcloud:apache
          name: nextcloud
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nextcloud
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: nextcloud
spec:
  routes:
    - match: HostSNI(`*`)
      services:
        - name: nextcloud
          port: 80
