steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - declaratiepdf
  - --project=<project-ID>
  - --region=europe-west1
  - --runtime=python39
  - --source=.
  - --trigger-http
  - --allow-unauthenticated
  - --no-gen2
